#include "printworker.h"

#include "app/session.h"

#include "sceneselectionmodel.h"

#include "graph/model/linegraphscene.h"
#include "graph/view/backgroundhelper.h"

#include <QPainter>

#include <QPrinter>
#include <QPdfWriter>
#include <QSvgGenerator>

#include "info.h"

#include <QFile>

#include <QDebug>

bool testFileIsWriteable(const QString& fileName, QString &errOut)
{
    QFile tmp(fileName);
    const bool existed = tmp.exists();
    bool writable = tmp.open(QFile::WriteOnly);
    errOut = tmp.errorString();

    if(tmp.isOpen())
        tmp.close();
    if(!existed)
        tmp.remove();

    return writable;
}

PrintWorker::PrintWorker(sqlite3pp::database &db, QObject *parent) :
    QObject(parent),
    differentFiles(false),
    outType(Print::Native)
{
    scene = new LineGraphScene(db, this);
}

void PrintWorker::setPrinter(QPrinter *printer)
{
    m_printer = printer;
}

void PrintWorker::setOutputType(Print::OutputType type)
{
    outType = type;
}

void PrintWorker::setFileOutput(const QString &value, bool different)
{
    fileOutput = value;
    if(fileOutput.endsWith('/'))
        fileOutput.chop(1);
    differentFiles = different;
}

void PrintWorker::setSelection(SceneSelectionModel *newSelection)
{
    selection = newSelection;
}

int PrintWorker::getMaxProgress() const
{
    return selection->getSelectionCount();
}

void PrintWorker::doWork()
{
    emit progress(0);

    switch (outType)
    {
    case Print::Native:
    {
        m_printer->setOutputFormat(QPrinter::NativeFormat);
        printPaged();
        break;
    }
    case Print::Pdf:
    {
        printPdf();
        break;
    }
    case Print::Svg:
    {
        printSvg();
        break;
    }
    }

    emit finished();
}

void PrintWorker::printInternal(BeginPaintFunc func, bool endPaintingEveryPage)
{
    QPainter painter;

    int progressVal = 0;
    bool firstPage = true;

    if(!selection->startIteration())
        return; //Error

    while (true)
    {
        const SceneSelectionModel::Entry entry = selection->getNextEntry();
        if(!entry.objectId)
            break; //Finished

        emit progress(progressVal++);

        if(!scene->loadGraph(entry.objectId, entry.type))
            continue; //Loading error, skip

        const QRectF sourceRect(QPointF(), scene->getContentSize());

        emit description(scene->getGraphObjectName());

        bool valid = true;
        if(func)
            valid = func(&painter, firstPage, scene->getGraphObjectName(), sourceRect);
        if(!valid)
            return;

        if(firstPage)
            firstPage = false;

        QRectF stationLabelRect = sourceRect;
        stationLabelRect.setHeight(Session->vertOffset - 5); //See LineGraphView::resizeHeaders()

        BackgroundHelper::drawBackgroundHourLines(&painter, sourceRect);
        BackgroundHelper::drawStations(&painter, scene, sourceRect);
        BackgroundHelper::drawJobStops(&painter, scene, sourceRect);
        BackgroundHelper::drawJobSegments(&painter, scene, sourceRect);
        BackgroundHelper::drawStationHeader(&painter, scene, stationLabelRect, 0);

        if(endPaintingEveryPage)
            painter.end();
    }
}

void PrintWorker::printSvg()
{
    std::unique_ptr<QSvgGenerator> svg;
    const QString docTitle = QStringLiteral("Timetable Session");
    const QString descr = QStringLiteral("Generated by %1").arg(AppDisplayName);

    const QString fmt = QString("%1/%2.svg").arg(fileOutput);

    auto beginPaint = [this, &svg, &fmt, &docTitle, &descr](QPainter *painter, bool firstPage,
                                                            const QString& title, const QRectF& sourceRect) -> bool
    {
        const QString fileName = fmt.arg(title);
        svg.reset(new QSvgGenerator);
        svg->setTitle(docTitle);
        svg->setDescription(descr);
        svg->setFileName(fileName);
        svg->setSize(sourceRect.size().toSize());
        svg->setViewBox(sourceRect);

        if(!painter->begin(svg.get()))
        {
            qWarning() << "PrintWorker::printSvg(): cannot begin QPainter";
            QString fileErr;
            bool writable = testFileIsWriteable(fileName, fileErr);

            QString msg;
            if(!writable)
            {
                msg = tr("SVG Error: cannot open output file.\n"
                         "Path: \"%1\"\n"
                         "Error: %2").arg(fileName, fileErr);
            }
            else
            {
                msg = tr("SVG Error: generic error.");
            }


            emit errorOccured(msg);
            return false;
        }

        return true;
    };

    printInternal(beginPaint, true);
}

void PrintWorker::printPdf()
{
    m_printer->setOutputFormat(QPrinter::PdfFormat);
    m_printer->setCreator(AppDisplayName);
    m_printer->setDocName(QStringLiteral("Timetable Session"));

    if(differentFiles)
    {
        printPdfMultipleFiles();
    }
    else
    {
        m_printer->setOutputFileName(fileOutput);
        printPaged();
    }
}

void PrintWorker::printPdfMultipleFiles()
{
    std::unique_ptr<QPdfWriter> writer;


    const QString fmt = QString("%1/%2.pdf").arg(fileOutput);

    auto beginPaint = [this, &writer, &fmt](QPainter *painter, bool firstPage,
                                            const QString& title, const QRectF& sourceRect) -> bool
    {
        const QString fileName = fmt.arg(title);
        writer.reset(new QPdfWriter(fileName));
        QPageSize ps(QPageSize::A4);
        writer->setPageSize(ps);

        if(!painter->begin(writer.get()))
        {
            qWarning() << "PrintWorker::printPdfMultipleFiles(): cannot begin QPainter";

            QString fileErr;
            bool writable = testFileIsWriteable(fileName, fileErr);

            QString msg;
            if(!writable)
            {
                msg = tr("PDF Error: cannot open output file.\n"
                         "Path: \"%1\"\n"
                         "Error: %2").arg(fileName, fileErr);
            }
            else
            {
                msg = tr("PDF Error: generic error.");
            }


            emit errorOccured(msg);
            return false;
        }

        const double scaleX = writer->width() / sourceRect.width();
        const double scaleY = writer->height() / sourceRect.height();
        const double scale = qMin(scaleX, scaleY);

        const QRectF win = painter->window();

        painter->fillRect(win, Qt::darkCyan);

        QFont f;
        f.setPointSize(10);
        painter->setFont(f);
        painter->drawText(painter->window().center(), "ciao");

        painter->scale(scale, scale);

        f.setPointSize(4);
        painter->setPen(Qt::red);
        painter->drawText(QPointF(10, 10), "BOB");

        return true;
    };

    printInternal(beginPaint, true);
}

void PrintWorker::printPaged()
{
    auto beginPaint = [this](QPainter *painter, bool firstPage,
                             const QString& title, const QRectF& sourceRect) -> bool
    {
        if(firstPage)
        {
            if(!painter->begin(m_printer))
            {
                qWarning() << "PrintWorker::printPaged(): cannot begin QPainter";
                emit errorOccured(tr("Cannot begin painting"));
                return false;
            }
        }
        else
        {
            if(!m_printer->newPage())
            {
                qWarning() << "PrintWorker::printPaged(): cannot add new page";
                emit errorOccured(tr("Cannot create new page"));
                return false;
            }
        }
        return true;
    };

    printInternal(beginPaint, false);
}
